/* AUTO-GENERATED by tools/build-manifest.mjs — do not edit by hand. */
window.IDASARA_MANIFEST = {
  "generatedAt": "2026-06-20T06:13:52.017Z",
  "stats": {
    "grades": 3,
    "mediums": 4,
    "subjects": 12,
    "clusters": 10,
    "lessons": 2
  },
  "grades": [
    {
      "slug": "grade-08",
      "title": "Grade 8",
      "sub": "",
      "order": 8,
      "mediums": [
        {
          "slug": "sinhala",
          "title": "Sinhala",
          "order": 2,
          "subjects": [
            {
              "slug": "science",
              "title": "Science",
              "icon": "🔬",
              "order": 1,
              "map": {
                "href": "content/grade-08/sinhala/science/_map.html",
                "title": "8 ශ්‍රේණිය විද්‍යාව — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "8 ශ්‍රේණිය විද්‍යාව — ක්ෂුද්‍ර ජීවීන් හා අපගේ ආහාර",
                  "href": "content/grade-08/sinhala/science/cluster-01.html",
                  "lessons": []
                }
              ]
            },
            {
              "slug": "mathematics",
              "title": "Mathematics",
              "icon": "🔢",
              "order": 2,
              "map": {
                "href": "content/grade-08/sinhala/mathematics/_map.html",
                "title": "8 ශ්‍රේණිය ගණිතය — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "8 ශ්‍රේණිය ගණිතය | සංඛ්‍යා පදනම",
                  "href": "content/grade-08/sinhala/mathematics/cluster-01.html",
                  "lessons": []
                }
              ]
            },
            {
              "slug": "english",
              "title": "English",
              "icon": "🔤",
              "order": 3,
              "map": {
                "href": "content/grade-08/sinhala/english/_map.html",
                "title": "8 ශ්‍රේණිය ඉංග්‍රීසි — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "Grade 8 English · Cluster 1 — Plan, Achieve, Learn Beyond",
                  "href": "content/grade-08/sinhala/english/cluster-01.html",
                  "lessons": []
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "grade-09",
      "title": "Grade 9",
      "sub": "",
      "order": 9,
      "mediums": [
        {
          "slug": "sinhala",
          "title": "Sinhala",
          "order": 2,
          "subjects": [
            {
              "slug": "science",
              "title": "Science",
              "icon": "🔬",
              "order": 1,
              "map": {
                "href": "content/grade-09/sinhala/science/_map.html",
                "title": "9 ශ්‍රේණිය විද්‍යාව — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "multi",
                  "num": 1,
                  "title": "9 ශ්‍රේණිය විද්‍යාව · පොකුර 1 — මානව සිරුර",
                  "href": "content/grade-09/sinhala/science/cluster-01/index.html",
                  "lessons": [
                    {
                      "num": 2,
                      "title": "ඇස හා කන (The Eye & Ear) | 9 ශ්‍රේණිය විද්‍යාව",
                      "href": "content/grade-09/sinhala/science/cluster-01/02-eye-ear.html"
                    },
                    {
                      "num": 6,
                      "title": "මානව රුධිර සංසරණ පද්ධතිය (Blood Circulation) | 9 ශ්‍රේණිය විද්‍යාව",
                      "href": "content/grade-09/sinhala/science/cluster-01/06-circulation.html"
                    }
                  ]
                }
              ]
            },
            {
              "slug": "mathematics",
              "title": "Mathematics",
              "icon": "🔢",
              "order": 2,
              "map": {
                "href": "content/grade-09/sinhala/mathematics/_map.html",
                "title": "9 ශ්‍රේණිය ගණිතය — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "9 ශ්‍රේණිය ගණිතය | සංඛ්‍යා හා ඒවායේ ස්වරූප",
                  "href": "content/grade-09/sinhala/mathematics/cluster-01.html",
                  "lessons": []
                }
              ]
            },
            {
              "slug": "english",
              "title": "English",
              "icon": "🔤",
              "order": 3,
              "map": {
                "href": "content/grade-09/sinhala/english/_map.html",
                "title": "9 ශ්‍රේණිය ඉංග්‍රීසි — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "Grade 9 English | Self, Talents & Wellbeing",
                  "href": "content/grade-09/sinhala/english/cluster-01.html",
                  "lessons": []
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "ol",
      "title": "O/L",
      "sub": "Grades 10–11",
      "order": 10.5,
      "mediums": [
        {
          "slug": "english",
          "title": "English",
          "order": 1,
          "subjects": [
            {
              "slug": "science",
              "title": "Science",
              "icon": "🔬",
              "order": 1,
              "map": {
                "href": "content/ol/english/science/_map.html",
                "title": "O/L Science Revision Map"
              },
              "clusters": []
            },
            {
              "slug": "mathematics",
              "title": "Mathematics",
              "icon": "🔢",
              "order": 2,
              "map": {
                "href": "content/ol/english/mathematics/_map.html",
                "title": "O/L Maths Revision Map"
              },
              "clusters": []
            },
            {
              "slug": "english",
              "title": "English",
              "icon": "🔤",
              "order": 3,
              "map": {
                "href": "content/ol/english/english/_map.html",
                "title": "O/L English Paper Map"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "O/L English | Paper I: Short Answers & Gap-Filling",
                  "href": "content/ol/english/english/cluster-01.html",
                  "lessons": []
                }
              ]
            }
          ]
        },
        {
          "slug": "sinhala",
          "title": "Sinhala",
          "order": 2,
          "subjects": [
            {
              "slug": "science",
              "title": "Science",
              "icon": "🔬",
              "order": 1,
              "map": {
                "href": "content/ol/sinhala/science/_map.html",
                "title": "සා/පෙළ විද්‍යාව — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "සා/පෙළ විද්‍යාව · ජීවය හා ජීවන ක්‍රියාවලි",
                  "href": "content/ol/sinhala/science/cluster-01.html",
                  "lessons": []
                }
              ]
            },
            {
              "slug": "mathematics",
              "title": "Mathematics",
              "icon": "🔢",
              "order": 2,
              "map": {
                "href": "content/ol/sinhala/mathematics/_map.html",
                "title": "සා/පෙළ ගණිතය — සම්පූර්ණ සිතියම"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "O/L ගණිතය · පාඩම 1 — සංඛ්‍යා පදනම",
                  "href": "content/ol/sinhala/mathematics/cluster-01.html",
                  "lessons": []
                }
              ]
            },
            {
              "slug": "english",
              "title": "English",
              "icon": "🔤",
              "order": 3,
              "map": {
                "href": "content/ol/sinhala/english/_map.html",
                "title": "සා/පෙළ ඉංග්‍රීසි — සම්පූර්ණ ප්‍රශ්න පත්‍රය"
              },
              "clusters": [
                {
                  "slug": "cluster-01",
                  "type": "single",
                  "num": 1,
                  "title": "සා/පෙළ ඉංග්‍රීසි | I ප්‍රශ්න පත්‍රය: කෙටි පිළිතුරු",
                  "href": "content/ol/sinhala/english/cluster-01.html",
                  "lessons": []
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
